---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform_ci:
    name: Terraform Validate & Plan
    runs-on: self-hosted
    environment: devops-poc  # Uses the environment where the secret is stored
    outputs:
      plan_file: terraform-plan.json
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Cloud Credentials
        shell: cmd
        run: |
          set gcloudPath=%USERPROFILE%\gcp-credentials.json
          echo %GCP_CREDENTIALS% > %gcloudPath%
          echo GOOGLE_APPLICATION_CREDENTIALS=%gcloudPath% >> %GITHUB_ENV%

      - name: Copy poc.auto.tfvars if available
        shell: cmd
        run: |
          set pocFile=%USERPROFILE%\poc.auto.tfvars
          if exist %pocFile% copy %pocFile% .

      - name: Terraform Validate
        shell: cmd
        run: terraform validate

  success_job:
    name: Success Notification
    runs-on: ubuntu-latest
    needs: terraform_ci
    steps:
      - name: Notify Success
        run: echo "Terraform plan was approved and ready to apply!"

